### ISSUE TITLE
Multiple Stream names - on the fly

### ISSUE THREAD

**Issue by citosid** [ryotarai/fluent-plugin-cloudwatch-logs#20]
I have one application that is creating streams on-the-fly, is there a way to use this plugin in such case?

**Comment by ryotarai** [comment]
If `auto_create_stream true` is set, log streams will be automatically created.

**Comment by GAHila** [comment]
What about consuming all streams under one log group? Log streams have a pattern but they have dynamic names. The answer above is for writing logs out to Cloudwatch. How about for reading from Cloudwatch?
