### ISSUE TITLE
InvalidSequenceTokenException

### ISSUE THREAD

**Issue by dmytroleonenko** [ryotarai/fluent-plugin-cloudwatch-logs#32]
We face an issue quite often:

> temporarily failed to flush the buffer. next_retry=2016-01-29 15:40:52 +0000 error_class="Aws::CloudWatchLogs::Errors::InvalidSequenceTokenException" error="The given sequenceToken is invalid. The next expected sequenceToken is: 49557948269779864971021949846578250090634309625148623890" plugin_id="object:3ffaeda886e4"

Any ideas?

**Comment by andreaslang** [comment]
This is usually caused if you log from different places to the same stream. I have a fork with a fix for it. I will create a pull request to discuss the solution.

**Comment by uMag** [comment]
@ryotarai Please merge PR

**Comment by zhaoyao91** [comment]
well, this issue seems still exit

**Comment by Seraf** [comment]
Hello,
I just ran into this issue this night also : 
```
2018-05-24 09:36:18 +0200 [warn]: #0 updating upload sequence token forcefully because unrecoverable error occured error_class=Aws::CloudWatchLogs::Errors::InvalidSequenceTokenException error="The given sequenceToken is invalid. The next expected sequenceToken is: 49581065914311687560974364860991990129098109324179326370" log_group="website-prod" log_stream="nginx-cycloid-access" new_sequence_token="49581065914311687560974364852036267657392934886127486370"
```
I have as @andreaslang said two servers logging to the same logstream, but the PR doesn't seems to have fixed the issue :(

**Comment by Seraf** [comment]
Said nothing, I have the logs of both servers in cloudwatch, I was wrong because of the message warn.
Is there a way to disable this warn message ?

**Comment by vitali-shcharbin** [comment]
Hello, this issue is still reproducible if log group name is the same for multiple pods for example:
```
        <record>
          stream_name ${record["kubernetes"]["container_name"]}
        </record>
```

Output:
```
updating upload sequence token forcefully because unrecoverable error occured error_class=Aws::CloudWatchLogs::Errors::InvalidSequenceTokenException error="The given sequenceToken is invalid. The next expected sequenceToken is:.....

retry succeeded
...
```
