### ISSUE TITLE
Using message_keys got error on empty log message

### ISSUE THREAD

**Issue by iwat** [ryotarai/fluent-plugin-cloudwatch-logs#37]
In my use case, I use Docker to send log message to fluentd. Some occasions, the container echoes an empty line and Docker simply forwards that to fluentd. I use `message_keys` to send only `log` message key and this plugin throws an error regarding an empty string problem.

```
<source>
  @type forward
  @label @mainstream
  port 24224
</source>
<label @mainstream>
  <match **>
    @type cloudwatch_logs
    use_tag_as_group true
    log_stream_name_key container_id
    message_keys log
    auto_create_stream true
  </match>
</label>
```

Example input record.

```
{
  "source": "stdout",
  "log": "",
  "container_id": "98e5d9eca1694a4b33dd668e48c0b477b402f542fa420931cef8579feb440a04",
  "container_name": "/austinecashtransaction_app_1"
}
```

My workaround is to add some more field to `message_keys` to ensure that final message has something.

```
message_keys source,log
```

**Comment by ryotarai** [comment]
I don't have a good idea to fix this. If you have it, please create a pull request

**Comment by nikolaygtitov** [comment]
Was there any fix for it? I keep getting empty WARNING and ERROR messages in fluentd type container. Please share your knowledge or fix if you have it.
