### ISSUE TITLE
Fluentd 0.14 support

### ISSUE THREAD

**Issue by ryotarai** [ryotarai/fluent-plugin-cloudwatch-logs#54]

**Comment by ashlineldridge** [comment]
Hi, thanks for your work on this plugin. I've found it very useful. Any chance you could offer Fluentd 0.14 support? Specifically millisecond resolution for CloudWatch log events?

**Comment by ryotarai** [comment]
> Any chance you could offer Fluentd 0.14 support? Specifically millisecond resolution for CloudWatch log events?

At this time, I do not have a plan to support millisecond resolution but a pull request is welcome!

**Comment by ashlineldridge** [comment]
No worries. Thanks, @ryotarai. If I can brush up my Ruby skills I'll have a shot at that PR! :-)

**Comment by kenden** [comment]
related https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/pull/67

**Comment by cosmo0920** [comment]
@kenden #67 is for v0.14 Compatibility layer.
Really v0.14 support is still needed.

**Comment by cosmo0920** [comment]
Hi, I sent #71 to support to use v0.14 API in this plugin.
Does anyone want to try this PR?

**Comment by rahul-chowdhury** [comment]
Hi, Any chance you could offer Fluentd 0.12 support? Specifically we use `td-agent` version 2.3.x.

**Comment by cosmo0920** [comment]
fluent-plugin-cloudwatch-logs v0.4.5 or older can work with Fluentd v0.12.

**Comment by rahul-chowdhury** [comment]
> fluent-plugin-cloudwatch-logs v0.4.5 or older can work with Fluentd v0.12.

@cosmo0920 Thanks a lot. It worked fine!
