### ISSUE TITLE
Support for IAM role rather than user

### ISSUE THREAD

**Issue by cesartl** [ryotarai/fluent-plugin-cloudwatch-logs#68]
Hi,

are you planning to support IAM role instead of having to give a secret key?

If requests to the AWS API are made within an EC2 instance running a specific role, it can get privilege from a policy without having to define access and secret keys.

Would it already work if the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are not passed?

thanks

**Comment by sampointer** [comment]
I'm working on this plugin which may do what you want: https://github.com/sampointer/fluent-plugin-cloudwatch-ingest

It is not yet ready for use but is in testing on a very high volume logging infrastructure.

**Comment by cesartl** [comment]
thanks @sampointer it looks quite useful indeed. I will keep an eye on your project and try to use when ready.

**Comment by cesartl** [comment]
@sampointer I'm actually looking into writing into Cloudwatch. Does your plugin support that too?

**Comment by sampointer** [comment]
No. Consumption only at the minute.

**Comment by sampointer** [comment]
I added cross-account IAM and STS to this plugin we're commenting on and use it as such today. It can be made to work. This plugin also supports writing to cloudwatch.

**Comment by cesartl** [comment]
thanks, is there any documentation on how to use it? I can always use the secret key but so far I've enjoyed doing everything with roles and not having to manage any keys!

**Comment by sampointer** [comment]
This is the STS via IAM docs: https://github.com/ryotarai/fluent-plugin-cloudwatch-logs#cross-account-operation

however underneath this uses the ruby aws sdk and so if there are no credentials supplied it'll pull them from the instance role. So, you should just be able to omit the two configuration options for the key and secret. If that doesn't work (I run with STS enabled) then use the STS instructions to have the box assume it's own IAM instance role!

**Comment by cesartl** [comment]
omitting secret and key worked. thanks
